# Generated by Django 4.1.1 on 2022-10-02 08:16

from django.db import migrations, models
import petstagram.main_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[petstagram.main_app.validators.validate_name])),
                ('last_name', models.CharField(max_length=30, validators=[petstagram.main_app.validators.validate_name])),
                ('picture', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=30, validators=[petstagram.main_app.validators.validate_email])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11)),
            ],
        ),
    ]
