# Generated by Django 4.1.1 on 2022-10-02 08:24

from django.db import migrations, models
import petstagram.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=30, unique=True, validators=[petstagram.main_app.validators.validate_email]),
        ),
    ]
