# Generated by Django 4.1.1 on 2022-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='EGN'),
        ),
    ]
